Repository DecidedCard/Porifo, pull requests merged in 2024-04, with the labels that each got.

#18 Main page
  public/1.png
  public/11.png
  public/2.png
  public/22.png
  public/3.png
  public/33.png
  public/porifo.svg
  src/Components/Footer.tsx
  src/Components/Header.tsx
  src/Components/MainPage/Cover.tsx
  src/Components/MainPage/MiddleLeft.tsx
  src/Components/MainPage/MiddleRight.tsx
  src/app/layout.tsx
  src/app/page.tsx
  tailwind.config.ts
Labels: 문서, 새로운 기능

#22 Feature/community
  package.json
  src/Components/Community/Cards.tsx
  src/Components/Community/api.ts
  yarn.lock
Labels: 버그, 문서, 새로운 기능

#23 ouaht 끝냈습니다~
  src/app/(authlayout)/layout.tsx
  src/app/(authlayout)/social_setting/page.tsx
  src/app/(nonAuthLayout)/signin/page.tsx
  src/app/(nonAuthLayout)/signup/page.tsx
  src/hooks/sign/useGetUser.ts
Labels: 새로운 기능

#25 Main page UI 완성
  public/4.png
  public/5.png
  public/6.png
  public/7.png
  public/임시.png
  src/Components/Commen/Button.tsx
  src/Components/Footer.tsx
  src/Components/Header.tsx
  src/Components/MainPage/Bottom.tsx
  src/Components/MainPage/Cover.tsx
  src/Components/MainPage/MiddleBottom.tsx
  src/Components/MainPage/MiddleImage.tsx
  src/Components/MainPage/MiddleLeft.tsx
  src/Components/MainPage/MiddleRight.tsx
  src/Components/MainPage/Recommendation.tsx
  src/app/page.tsx
  tailwind.config.ts
  yarn.lock
Labels: 문서, 새로운 기능

#30 Main page
  src/Components/Footer.tsx
  src/Components/Header.tsx
  src/Components/MainPage/Recommendation.tsx
  src/app/page.tsx
Labels: 문서, 새로운 기능

#32 Feature/community
  src/Components/Community/Cards.tsx
  src/Components/Community/Filter.tsx
  src/Components/Community/api.ts
  src/app/community/page.tsx
Labels: 문서, 새로운 기능

#35 Main page
  package.json
  src/Components/MyPage/Buttons.tsx
  src/Components/MyPage/Introduction.tsx
  src/Components/MyPage/Navigation.tsx
  src/Components/MyPage/Portfolio.tsx
  src/Components/MyPage/Project.tsx
  src/Components/MyPage/URL.tsx
  src/Components/MyPage/UserInfo.tsx
  src/Components/MyPageComponents/Navigation.tsx
  src/app/(authlayout)/mypage/[id]/page.tsx
  src/app/(authlayout)/mypage/page.tsx
  src/app/(nonAuthLayout)/guest/page.tsx
  yarn.lock
Labels: 문서, 새로운 기능

#40 mypage 코드 리팩토링
  src/Components/MyPage/UserInfo.tsx
  src/hooks/mypage/useMyPage.ts
  src/hooks/mypage/usePortfolio.ts
  src/util/query_key.ts
  src/util/select_list.ts
Labels: 문서

#42 Main page
  src/Components/Commen/Input.tsx
  src/Components/Footer.tsx
  src/Components/Header.tsx
  src/Components/MainPage/Bottom.tsx
  src/Components/MyPage/Buttons.tsx
  src/Components/MyPage/UserInfo.tsx
  src/app/(authlayout)/mypage/page.tsx
Labels: 문서, 새로운 기능

#44 input form 유효성 검사 작성
  src/Components/MyPage/Buttons.tsx
  src/Components/MyPage/Portfolio.tsx
  src/Components/MyPage/UserInfo.tsx
  src/app/(authlayout)/mypage/page.tsx
  src/hooks/mypage/useInfo.ts
  src/hooks/mypage/useMyPage.ts
  src/hooks/mypage/useProject.ts
  src/hooks/sign/useGetUser.ts
  src/store/portfolioInfoStore.ts
  src/store/projectStore.ts
  src/store/userStore.ts
  src/types/PortfolioInfo.ts
  src/util/input_form_validation.ts
Labels: 문서, 새로운 기능

#49 mypage ui 작업
  src/Components/Commen/Input.tsx
  src/Components/MyPage/Introduction.tsx
  src/Components/MyPage/PortfolioUrl.tsx
  src/Components/MyPage/Project.tsx
  src/Components/MyPage/URL.tsx
  src/Components/MyPage/UserInfo.tsx
  src/app/(authlayout)/mypage/page.tsx
  src/app/(nonAuthLayout)/guest/page.tsx
  src/app/globals.css
  src/hooks/mypage/useInfo.ts
  src/hooks/mypage/useProject.ts
Labels: 문서

#51 Sign 기본 css 설정
  public/formLogo.svg
  public/github.svg
  public/google.svg
  public/kakao.svg
  src/Components/Commen/Input.tsx
  src/Components/Sign/SocialSign.tsx
  src/app/(authlayout)/social_setting/page.tsx
  src/app/(nonAuthLayout)/signin/page.tsx
  src/app/(nonAuthLayout)/signup/page.tsx
  src/app/(nonAuthLayout)/signup_method/page.tsx
  src/util/sign/socialLogin.ts
Labels: 새로운 기능, 도와주세요

#52 Main page
  public/vector-193.svg
  src/Components/MainPage/Bottom.tsx
  src/Components/MyPage/UserInfo.tsx
  src/app/(nonAuthLayout)/signup_method/page.tsx
Labels: 새로운 기능

#55 Feature/input form
  src/Components/Commen/Button.tsx
  src/Components/Header.tsx
  src/Components/MyPage/UserInfo.tsx
  src/hooks/mypage/useInfo.ts
  src/hooks/mypage/useProject.ts
  src/store/careerStore.ts
  src/store/portfolioInfoStore.ts
  src/types/Career.ts
  src/types/PortfolioInfo.ts
  src/types/Supabase.ts
Labels: 문서, 새로운 기능

#57 프로젝트, 업무경력 미리보기 작성
  src/Components/Commen/Button.tsx
  src/Components/Header.tsx
  src/Components/MainPage/Bottom.tsx
  src/Components/MainPage/Cover.tsx
  src/Components/MainPage/MiddleLeft.tsx
  src/Components/MyPage/Buttons.tsx
  src/Components/MyPage/Portfolio.tsx
  src/Components/MyPage/Project.tsx
  src/Components/MyPage/UserInfo.tsx
  src/app/(nonAuthLayout)/guest/page.tsx
  src/app/(nonAuthLayout)/signin/page.tsx
  src/app/(nonAuthLayout)/signup/page.tsx
  src/app/(nonAuthLayout)/signup_method/page.tsx
  src/hooks/mypage/useInfo.ts
  src/hooks/mypage/useProject.ts
  src/store/careerStore.ts
  src/types/PortfolioInfo.ts
  src/util/supabase/portfolioInfo_supabase_DB.ts
Labels: 문서, 새로운 기능

#60 Feature/detail
  src/Components/Community/Cards.tsx
  src/Components/Community/Filter.tsx
  src/Components/DetailPage/Detail.tsx
  src/Components/DetailPage/Portfolio_detail.tsx
  src/app/community/page.tsx
  src/app/detail/[id]/page.tsx
  src/util/query_key.ts
  src/util/select_list.ts
  src/util/supabase/community_filter_DB.ts
Labels: 문서, 새로운 기능

#61 SignUp과 SignIn에 필요한 기능 및 css 추가
  public/eye.svg
  public/eye_close.svg
  public/find_password_arrow.svg
  public/github.svg
  public/google.svg
  public/kakao.svg
  src/Components/Commen/Input.tsx
  src/Components/Header.tsx
  src/Components/Sign/SignUpItem.tsx
  src/Components/Sign/SocialSign.tsx
  src/app/(nonAuthLayout)/password_change/page.tsx
  src/app/(nonAuthLayout)/signin/page.tsx
  src/app/(nonAuthLayout)/signup/page.tsx
Labels: 새로운 기능

#62 url copy, pdf download
  src/Components/MyPage/Buttons.tsx
  src/Components/MyPage/Portfolio.tsx
  src/app/(authlayout)/mypage/[id]/page.tsx
  src/app/create/[id]/page.tsx
  src/store/userStore.ts
  src/types/User.ts
  src/util/urlCopy.ts
Labels: 문서, 새로운 기능

#68 Feature/community
  postcss.config.js
  public/arrow-down.svg
  public/arrow-up.svg
  public/frame-13740.svg
  public/frame-13741.svg
  public/frame-13742.svg
  public/frame-13743.svg
  public/icon-set1.svg
  public/icon-set3.svg
  public/icon-set5.svg
  public/icon-set7.svg
  public/icon-set8.svg
  public/icon-set9.svg
  public/rectangle-1150.png
  public/rectangle-1151.png
  public/rectangle-1152.png
  public/rectangle-1153.png
  public/rectangle0.png
  public/rectangle1.png
  public/rectangle2.png
  public/rectangle3.png
  src/Components/Community/Cards.tsx
  src/Components/Community/Carousel.tsx
  src/Components/Community/Dropdown.tsx
  src/Components/Community/Filter.tsx
  src/Components/Community/JobFilter.tsx
  src/app/community/page.tsx
  src/hooks/useSupabaseRange.ts
  src/store/jobFilterStore.ts
  src/store/pageStore.ts
  src/util/supabase/community_filter_DB.ts
  tailwind.config.ts
Labels: 문서, 새로운 기능

#72 input form 프로젝트 로직 변경 및 저장 로직 변경, 한줄 소개 작성
  src/Components/MyPage/Buttons.tsx
  src/Components/MyPage/Introduction.tsx
  src/Components/MyPage/PortfolioUrl.tsx
  src/Components/MyPage/Project.tsx
  src/Components/MyPage/UserInfo.tsx
  src/app/(authlayout)/mypage/page.tsx
  src/hooks/mypage/useInfo.ts
  src/hooks/mypage/useProject.ts
  src/store/careerStore.ts
  src/store/portfolioInfoStore.ts
  src/store/projectStore.ts
  src/types/PortfolioInfo.ts
  src/types/Supabase.ts
  tsconfig.json
Labels: 문서, 새로운 기능

#74 Feature/input form
  src/Components/MyPage/Careers.tsx
  src/Components/MyPage/Education.tsx
  src/Components/MyPage/Portfolio.tsx
  src/Components/MyPage/Project.tsx
  src/Components/MyPage/UserInfo.tsx
  src/app/(authlayout)/mypage/page.tsx
  src/hooks/mypage/useCareer.ts
  src/hooks/mypage/useEducation.ts
  src/hooks/mypage/useInfo.ts
  src/hooks/mypage/useMyPage.ts
  src/store/careerStore.ts
  src/store/educationStore.ts
  src/store/portfolioInfoStore.ts
  src/store/projectStore.ts
  src/types/PortfolioInfo.ts
  src/types/Supabase.ts
  src/types/education.ts
  src/util/input_form_validation.ts
Labels: 문서, 새로운 기능

#78 Template 1번, 2번 제작
  src/Components/MainPage/Bottom.tsx
  src/Components/MainPage/Recommendation.tsx
  src/Components/MyPage/Education.tsx
  src/Components/Template one/Middle.tsx
  src/Components/Template one/Top.tsx
  src/Components/Template one/URL.tsx
  src/Components/Template two/Bottom.tsx
  src/Components/Template two/Middle.tsx
  src/Components/Template two/Top.tsx
  src/Components/Template two/URL.tsx
  src/Components/Template/Bottom.tsx
  src/Components/Template/Middle.tsx
  src/Components/Template/URL.tsx
  src/Components/TimeLine/Project.tsx
  src/Components/TimeLine/ProjectTimelineItem.tsx
  src/Components/TimeLine/UserProject.tsx
  src/Components/TimeLine/WorkExperience.tsx
  src/Components/TimeLine/WorkTimelineItem.tsx
  src/app/template/[id]/page.tsx
  src/app/templateOne/[id]/page.tsx
  src/app/templateTwo/[id]/page.tsx
Labels: 문서, 새로운 기능

#79 버튼과 입력값에 대한 css와 기능 설정
  package.json
  src/Components/Sign/SignButton.tsx
  src/Components/Sign/SignEmailValidate.tsx
  src/Components/Sign/SignPasswordValidate.tsx
  src/Components/Sign/SignUpItem.tsx
  src/Components/Sign/SignValidate.tsx
  src/app/(authlayout)/social_setting/page.tsx
  src/app/(nonAuthLayout)/find_email/page.tsx
  src/app/(nonAuthLayout)/password_change/page.tsx
  src/app/(nonAuthLayout)/signin/page.tsx
  src/app/(nonAuthLayout)/signup/page.tsx
  src/app/(nonAuthLayout)/signup_method/page.tsx
  src/middleware.ts
  src/util/sign/onlyNumber.ts
  src/util/sign/password_validate.ts
  src/util/sign/signNumber_validation.ts
  src/util/sign/sign_validate.ts
  yarn.lock
Labels: 새로운 기능

#80 메인페이지 수정, 커뮤니티 페이지에서 쓸 svg파일 저장
  public/grayEye.svg
  public/grayHeart.svg
  public/redHeart.svg
  src/Components/Header.tsx
  src/Components/MainPage/Bottom.tsx
  src/Components/MainPage/MiddleBottom.tsx
  src/Components/MainPage/MiddleImage.tsx
  src/Components/MainPage/MiddleLeft.tsx
  src/Components/MainPage/MiddleRight.tsx
  src/Components/MainPage/Recommendation.tsx
  tailwind.config.ts
Labels: 문서, 새로운 기능

#82 Feature/community
  public/blackMinus.svg
  src/Components/Community/Cards.tsx
  src/Components/Community/Carousel.tsx
  src/Components/Community/Filter.tsx
  src/Components/Community/JobFilter.tsx
  src/app/community/page.tsx
  src/util/supabase/community_filter_DB.ts
Labels: 문서, 새로운 기능

#86 Template
  src/Components/MainPage/Recommendation.tsx
  src/Components/Template one/Middle.tsx
  src/Components/Template one/Top.tsx
  src/Components/Template one/URL.tsx
  src/Components/TimeLine/ProjectTimelineItem.tsx
Labels: 문서, 새로운 기능

#88 Feature/community
  src/Components/Community/Cards.tsx
  src/Components/Community/Filter.tsx
  src/Components/DetailPage/Comments.tsx
  src/Components/DetailPage/Modal.tsx
  src/Components/DetailPage/Portfolio_detail.tsx
  src/app/detail/[id]/page.tsx
  src/store/detailStore.ts
  src/util/query_key.ts
  src/util/supabase/supabase_comments.ts
Labels: 문서

#99 [Feat: #94] - 유저의 포트폴리오 유무에 따라 다른 페이지 이동 완성
  src/Components/Sign/SignButton.tsx
  src/Components/Sign/SignPasswordValidate.tsx
  src/Components/Sign/SignPhoneNumber.tsx
  src/Components/Sign/SignRouterButton.tsx
  src/Components/Sign/SignSelectSex.tsx
  src/Components/Sign/SignUpItem.tsx
  src/Components/Sign/SignUploadBitrthDay.tsx
  src/Components/Sign/SocialSign.tsx
  src/app/(nonAuthLayout)/signin/page.tsx
  src/app/(nonAuthLayout)/signupMethod/page.tsx
  src/util/sign/signCheckUserPortfolio.ts
  src/util/sign/signNumber_validation.ts
  src/util/sign/socialLogin.ts
Labels: 새로운 기능, good first issue

#100 Feature/community
  src/Components/Community/Cards.tsx
  src/Components/DetailPage/CommentInput.tsx
  src/Components/DetailPage/Comments.tsx
  src/types/User.ts
  src/util/supabase/supabase_comments.ts
Labels: 문서, 새로운 기능

#101 코드 수정
  src/Components/Header.tsx
  src/Components/Sign/SignPhoneNumber.tsx
  src/app/(authlayout)/socialSetting/page.tsx
  src/app/(nonAuthLayout)/findEmail/page.tsx
  src/app/(nonAuthLayout)/signup/page.tsx
  src/util/sign/signPhoneNumberUtill.ts
Labels: 버그

#103 Template
  README.md
  public/11.png
  public/22.png
  public/33.png
  public/headerlogout.svg
  public/headerwrite.svg
  public/mainImage1.svg
  public/mainImage10.svg
  public/mainImage2.svg
  public/mainImage3.svg
  public/mainImage8.svg
  public/mainImage9.svg
  public/mainpeple1.png
  public/mainpeple2.png
  public/mainpeple3.png
  public/mainpeple4.png
  public/mainpeple5.png
  public/mainpeple6.png
  public/mainpeple7.png
  public/임시.png
  src/Components/Header.tsx
  src/Components/MainPage/Bottom.tsx
  src/Components/MainPage/MiddleBottom.tsx
  src/Components/MainPage/MiddleImage.tsx
  src/Components/MainPage/MiddleLeft.tsx
  src/Components/MainPage/MiddleRight.tsx
  src/Components/MainPage/Recommendation.tsx
  src/Components/Template one/Middle.tsx
  src/Components/TimeLine/ProjectTimelineItem.tsx
  tailwind.config.ts
Labels: 문서, 새로운 기능

#105 [Move:#102] - 퍼블릭 assets 파일 이동 후 경로 수정
  public/assets/image/headerlogout.svg
  public/assets/image/headerwrite.svg
  public/assets/image/mainImage1.svg
  public/assets/image/mainImage10.svg
  public/assets/image/mainImage2.svg
  public/assets/image/mainImage3.svg
  public/assets/image/mainImage8.svg
  public/assets/image/mainImage9.svg
  public/assets/image/mainpeple1.png
  public/assets/image/mainpeple2.png
  public/assets/image/mainpeple3.png
  public/assets/image/mainpeple4.png
  public/assets/image/mainpeple5.png
  public/assets/image/mainpeple6.png
  public/assets/image/mainpeple7.png
  public/assets/image/profile.svg
  src/Components/Header.tsx
  src/Components/MainPage/Bottom.tsx
  src/Components/MainPage/MiddleImage.tsx
  src/Components/MainPage/MiddleRight.tsx
Labels: 문서

#109 디테일 페이지 푸터, 헤더 안보이게 수정
  src/Components/DetailPage/Modal.tsx
  src/Components/Footer.tsx
  src/Components/Header.tsx
Labels: 문서

#111 자잘한 버그 수정
  next.config.mjs
  src/Components/Community/Cards.tsx
  src/Components/Community/Carousel.tsx
  src/Components/Community/JobFilter.tsx
  src/Components/DetailPage/Comments.tsx
  src/Components/DetailPage/LikeShare.tsx
  src/Components/DetailPage/Portfolio_detail.tsx
  src/Components/Footer.tsx
  src/Components/Header.tsx
  src/Components/Loading.tsx
  src/Components/LoginCheckModal.tsx
  src/Components/MyPage/Buttons.tsx
  src/Components/MyPage/Preview.tsx
  src/Components/MyPage/TemplateSelect.tsx
  src/Components/Template one/Middle.tsx
  src/Components/Template one/Standard.tsx
  src/Components/Template one/Top.tsx
  src/Components/Template one/URL.tsx
  src/Components/Template two/Bottom.tsx
  src/Components/Template two/Grid.tsx
  src/Components/Template two/Top.tsx
  src/Components/TimeLine/ProjectTimelineItem.tsx
  src/Components/TimeLine/UserProject.tsx
  src/Components/TimeLine/WorkExperience.tsx
  src/app/(authlayout)/layout.tsx
  src/app/(authlayout)/mypage/page.tsx
  src/app/(nonAuthLayout)/guest/page.tsx
  src/app/(nonAuthLayout)/guest/result/page.tsx
  src/app/create/[id]/page.tsx
  src/app/passwordChange/page.tsx
  src/hooks/guest/useGuestButton.ts
  src/hooks/mypage/useCareer.ts
  src/hooks/mypage/useInfo.ts
  src/hooks/mypage/useLoginCheck.ts
  src/hooks/mypage/usePortfolioQuery.ts
  src/hooks/mypage/useTemplateSelect.ts
  src/util/input_form_validation.ts
Labels: 문서

#115 Template
  README.md
Labels: 문서

#126 기술 스택 작성
  src/Components/MyPage/Introduction.tsx
  src/Components/MyPage/UserInfo.tsx
  src/app/(authlayout)/mypage/page.tsx
  src/hooks/mypage/useInfo.ts
  src/store/portfolioInfoStore.ts
  src/types/PortfolioInfo.ts
  src/types/Supabase.ts
  src/util/skill_tag.ts
Labels: 문서, 새로운 기능

#129 Template
  public/assets/image/download.svg
  public/assets/image/link.svg
  public/assets/image/mypagedefault.svg
  src/Components/Commen/Input.tsx
  src/Components/DetailPage/Portfolio_detail.tsx
  src/Components/MyPage/Buttons.tsx
  src/Components/MyPage/Careers.tsx
  src/Components/MyPage/Introduction.tsx
  src/Components/MyPage/Navigation.tsx
  src/Components/MyPage/Preview.tsx
  src/Components/MyPage/TemplateSelect.tsx
  src/Components/MyPage/UserInfo.tsx
  src/store/portfolioInfoStore.ts
  tailwind.config.ts
Labels: 문서, 새로운 기능

#132 마이페이지 UI 작업
  src/Components/MyPage/Buttons.tsx
  src/Components/MyPage/Introduction.tsx
  src/Components/MyPage/Navigation.tsx
  src/Components/MyPage/PortfolioUrl.tsx
  src/Components/MyPage/Project.tsx
Labels: 문서

#135 버그 fix 및 ui 수정
  src/Components/Guest/Buttons.tsx
  src/Components/MyPage/Buttons.tsx
  src/Components/MyPage/Careers.tsx
  src/Components/MyPage/Introduction.tsx
  src/Components/MyPage/Navigation.tsx
  src/Components/MyPage/PortfolioUrl.tsx
  src/Components/MyPage/Project.tsx
  src/Components/MyPage/UserInfo.tsx
  src/app/(nonAuthLayout)/guest/page.tsx
  src/app/create/[id]/page.tsx
  src/app/layout.tsx
  src/hooks/mypage/useInfo.ts
  src/hooks/mypage/usePortfolioQuery.ts
  src/hooks/mypage/useProject.ts
  src/store/portfolioInfoStore.ts
  src/util/input_form_validation.ts
Labels: 문서

#136 [Refactor] - 코드 수정
  src/Components/MyPage/Careers.tsx
  src/app/favicon.ico
  src/hooks/mypage/useInfo.ts
  src/hooks/mypage/usePortfolioQuery.ts
Labels: 문서

#141 [Feat] - input 필수 작성란 확인 수정
  public/templateImage/Grid_template.png
  public/templateImage/Standard_template.png
  src/Components/DetailPage/LikeShare.tsx
  src/Components/Header.tsx
  src/Components/MyPage/Buttons.tsx
  src/Components/MyPage/Introduction.tsx
  src/Components/MyPage/Navigation.tsx
  src/Components/MyPage/PortfolioUrl.tsx
  src/Components/MyPage/Project.tsx
  src/Components/MyPage/UserInfo.tsx
  src/Components/Template one/Middle.tsx
  src/Components/Template one/URL.tsx
  src/Components/Template two/URL.tsx
  src/Components/TimeLine/ProjectTimelineItem.tsx
  src/Components/TimeLine/UserProject.tsx
  src/app/(authlayout)/mypage/page.tsx
  src/app/create/[id]/page.tsx
  src/hooks/mypage/useInfo.ts
  src/hooks/mypage/usePortfolioQuery.ts
  src/hooks/mypage/useProject.ts
  src/util/input_form_validation.ts
Labels: 문서

#142 프로젝트 체크 시 2개 이상일 때 사라지지 않는 오류 해결
  src/Components/MyPage/Navigation.tsx
  src/Components/Template one/Standard.tsx
  src/app/favicon.ico
  src/util/input_form_validation.ts
Labels: 문서

#144 socialSetting과 phoneNumber 변경
  src/Components/Commen/Input.tsx
  src/Components/Sign/SignButton.tsx
  src/Components/Sign/SignSelectSex.tsx
  src/app/(authlayout)/socialSetting/page.tsx
  src/app/(nonAuthLayout)/signup/page.tsx
  src/util/sign/signNumber_validation.ts
Labels: 새로운 기능

#145 Template
  src/Components/MyPage/Navigation.tsx
  src/Components/Template one/Middle.tsx
  src/Components/Template one/URL.tsx
  src/Components/Template two/URL.tsx
  src/Components/TimeLine/ProjectTimelineItem.tsx
  src/Components/TimeLine/UserProject.tsx
Labels: 문서, 새로운 기능

#152 Style: border 수정및 약관 추가
  src/Components/HeaderNonAuth.tsx
  src/Components/Sign/SignPersonalInfoCheck.tsx
  src/app/(authlayout)/socialSetting/page.tsx
  src/app/(nonAuthLayout)/(findPassword)/findEmail/page.tsx
  src/app/(nonAuthLayout)/(findPassword)/passwordChange/page.tsx
  src/app/(nonAuthLayout)/signin/page.tsx
  src/app/(nonAuthLayout)/signup/page.tsx
  src/app/(nonAuthLayout)/signupMethod/page.tsx
  src/app/(nonAuthLayout)/welcome/page.tsx
Labels: 문서

#157 메인페이지 추천개발자 작업 완료
  src/Components/MainPage/Recommendation.tsx
  src/Components/Template one/Middle.tsx
  src/Components/TimeLine/ProjectTimelineItem.tsx
Labels: 문서, 새로운 기능

#158 input form 작성
  src/Components/Header.tsx
  src/Components/MyPage/UserInfo.tsx
  src/app/layout.tsx
  src/hooks/mypage/useInfo.ts
  src/hooks/mypage/useLoginCheck.ts
  src/store/portfolioInfoStore.ts
  src/types/PortfolioInfo.ts
  src/types/Supabase.ts
  src/types/User.ts
  src/util/supabase/portfolioInfo_supabase_DB.ts
  src/util/supabase/supabase_user.ts
Labels: 문서, 새로운 기능

#162 Feat: 현재 사용할 수 없는 회원가입 기능 주석 처리
  src/app/(nonAuthLayout)/signin/page.tsx
  src/app/(nonAuthLayout)/signupMethod/page.tsx
Labels: 도와주세요

#169 메인 페이지 이미지 교체, 푸터 완성, 404 페이지 완성
  public/assets/image/404.svg
  public/assets/image/mail.svg
  public/assets/image/slide1.svg
  public/assets/image/slide2.svg
  public/assets/image/slide3.svg
  public/assets/image/slide4.svg
  public/assets/image/slide5.svg
  public/assets/image/slide6.svg
  public/assets/image/slide7.svg
  public/assets/image/tel.svg
  src/Components/Footer.tsx
  src/Components/MainPage/Bottom.tsx
  src/Components/MainPage/MiddleImage.tsx
  src/Components/Template one/Middle.tsx
  src/Components/Template one/Top.tsx
  src/Components/Template one/URL.tsx
  src/Components/Template two/Top.tsx
  src/Components/Template two/URL.tsx
  src/Components/TimeLine/ProjectTimelineItem.tsx
  src/Components/TimeLine/UserProject.tsx
  src/app/[...404]/page.tsx
  src/app/not-found.tsx
  src/app/page.tsx
  tailwind.config.ts
Labels: 문서, 새로운 기능

#170 Feature/community
  src/Components/Community/Cards.tsx
  src/Components/Community/Carousel.tsx
  src/Components/Community/Dropdown.tsx
  src/Components/DetailPage/CommentInput.tsx
  src/Components/DetailPage/LikeShare.tsx
  src/Components/DetailPage/Portfolio_detail.tsx
  src/app/community/page.tsx
  src/store/portfolioInfoStore.ts
  src/types/PortfolioInfo.ts
  src/types/Supabase.ts
  src/util/query_key.ts
  src/util/supabase/community_filter_DB.ts
  src/util/supabase/detail_supabase_DB.ts
Labels: 문서, 새로운 기능

#171 Template
  public/assets/image/gray2Heart.svg
  src/Components/Community/Cards.tsx
  src/Components/DetailPage/CommentInput.tsx
  src/Components/DetailPage/Comments.tsx
  src/Components/DetailPage/LikeShare.tsx
  src/Components/DetailPage/Portfolio_detail.tsx
  src/Components/MainPage/Recommendation.tsx
  src/Components/Template one/Middle.tsx
  src/Components/Template one/Top.tsx
  src/Components/Template one/URL.tsx
  src/Components/Template two/Top.tsx
  src/Components/Template two/URL.tsx
  src/Components/TimeLine/ProjectTimelineItem.tsx
  src/Components/TimeLine/WorkExperience.tsx
  src/Components/TimeLine/WorkTimelineItem.tsx
  tailwind.config.ts
Labels: 문서, 새로운 기능

#202 input 태그 작성
  public/search.svg
  src/Components/MyPage/Buttons.tsx
  src/Components/MyPage/Introduction.tsx
  src/hooks/mypage/useInfo.ts
  src/util/getformatDate.ts
Labels: 문서, 새로운 기능

#203 Feature/community
  public/blackComment.svg
  public/gray_warn_lined.svg
  public/share.svg
  src/Components/Community/Cards.tsx
  src/Components/Community/Carousel.tsx
  src/Components/DetailPage/LikeShare.tsx
  src/Components/DetailPage/Modal.tsx
  src/Components/Header.tsx
  src/app/community/page.tsx
  src/hooks/community/useLiked.ts
  src/util/supabase/community_filter_DB.ts
Labels: 문서, 새로운 기능

#205 템플릿 Modern, Box 추가, 메인페이지 반응형 완성
  public/templateImage/Box_template.png
  public/templateImage/Grid_template.png
  public/templateImage/Modern_template.png
  public/templateImage/Standard_template.png
  src/Components/Commen/Button.tsx
  src/Components/DetailPage/Portfolio_detail.tsx
  src/Components/Footer.tsx
  src/Components/Guest/Buttons.tsx
  src/Components/Header.tsx
  src/Components/MainPage/Bottom.tsx
  src/Components/MainPage/Cover.tsx
  src/Components/MainPage/MiddleBottom.tsx
  src/Components/MainPage/MiddleImage.tsx
  src/Components/MainPage/MiddleLeft.tsx
  src/Components/MainPage/MiddleRight.tsx
  src/Components/MainPage/Recommendation.tsx
  src/Components/MyPage/Buttons.tsx
  src/Components/MyPage/Preview.tsx
  src/Components/MyPage/Project.tsx
  src/Components/MyPage/TemplateSelect.tsx
  src/Components/Template Box/Bottom.tsx
  src/Components/Template Box/Box.tsx
  src/Components/Template Box/Middle.tsx
  src/Components/Template Box/Top.tsx
  src/Components/Template Box/URL.tsx
  src/Components/Template Grid/Bottom.tsx
  src/Components/Template Grid/Grid.tsx
  src/Components/Template Grid/Middle.tsx
  src/Components/Template Grid/Top.tsx
  src/Components/Template Grid/URL.tsx
  src/Components/Template Modern/Bottom.tsx
  src/Components/Template Modern/Middle.tsx
  src/Components/Template Modern/Modern.tsx
  src/Components/Template Modern/Top.tsx
  src/Components/Template Modern/URL.tsx
  src/Components/Template Standard/Middle.tsx
  src/Components/Template Standard/Standard.tsx
  src/Components/Template Standard/Top.tsx
  src/Components/Template Standard/URL.tsx
  src/Components/TimeLine/ProjectTimelineItem.tsx
  src/Components/TimeLine/UserProject.tsx
  src/Components/TimeLine/WorkExperience.tsx
  src/Components/TimeLine/WorkTimelineItem.tsx
  src/app/(nonAuthLayout)/guest/result/page.tsx
  src/app/create/[id]/page.tsx
  src/app/page.tsx
  src/app/share/[id]/page.tsx
  tailwind.config.ts
Labels: 문서, 새로운 기능

#206 Sign email기능 구현 중
  src/Components/Sign/SignButton.tsx
  src/Components/Sign/SignEmailTemplate.tsx
  src/Components/Sign/SignRouterButton.tsx
  src/app/(nonAuthLayout)/(findPassword)/layout.tsx
  src/app/(nonAuthLayout)/confirmEmail/page.tsx
  src/app/(nonAuthLayout)/signin/page.tsx
  src/app/(nonAuthLayout)/signup/page.tsx
  src/app/api/send/route.ts
  src/app/auth/confirm/route.ts
Labels: 새로운 기능

#216 마이페이지, 디테일 페이지, 메인페이지 반응형 완료
  src/Components/DetailPage/Portfolio_detail.tsx
  src/Components/Footer.tsx
  src/Components/Header.tsx
  src/Components/MainPage/Bottom.tsx
  src/Components/MainPage/Cover.tsx
  src/Components/MainPage/MiddleImage.tsx
  src/Components/MainPage/MiddleLeft.tsx
  src/Components/MyPage/Buttons.tsx
  src/Components/MyPage/Introduction.tsx
  src/Components/MyPage/Navigation.tsx
  src/Components/MyPage/PortfolioUrl.tsx
  src/Components/MyPage/Preview.tsx
  src/Components/MyPage/Project.tsx
  src/Components/MyPage/UserInfo.tsx
  src/Components/Template Box/Bottom.tsx
  src/Components/Template Box/Middle.tsx
  src/Components/Template Box/Top.tsx
  src/Components/Template Box/URL.tsx
  src/Components/Template Grid/Bottom.tsx
  src/Components/Template Grid/Middle.tsx
  src/Components/Template Grid/Top.tsx
  src/Components/Template Grid/URL.tsx
  src/Components/Template Modern/Bottom.tsx
  src/Components/Template Modern/Middle.tsx
  src/Components/Template Modern/Top.tsx
  src/Components/Template Modern/URL.tsx
  src/Components/Template Standard/Middle.tsx
  src/Components/Template Standard/Top.tsx
  src/Components/Template Standard/URL.tsx
  src/Components/TimeLine/ProjectTimelineItem.tsx
  src/Components/TimeLine/UserProject.tsx
  src/Components/TimeLine/WorkExperience.tsx
  src/Components/TimeLine/WorkTimelineItem.tsx
  src/app/(authlayout)/mypage/page.tsx
  src/app/page.tsx
Labels: 문서, 새로운 기능

#218 layout 개별 적용
  src/Components/Header.tsx
  src/Components/HeaderNonAuth.tsx
  src/app/(authlayout)/layout.tsx
  src/app/(nonAuthLayout)/(findPassword)/findEmail/page.tsx
  src/app/(nonAuthLayout)/layout.tsx
  src/app/community/layout.tsx
  src/app/create/layout.tsx
  src/app/layout.tsx
  src/app/page.tsx
  src/app/share/layout.tsx
Labels: 문서, 새로운 기능

#221 상세페이지 모달 반응형
  public/assets/image/comunity.svg
  src/Components/DetailPage/Modal.tsx
  src/Components/DetailPage/Portfolio_detail.tsx
  src/Components/Footer.tsx
  src/Components/Header.tsx
  src/Components/MainPage/MiddleImage.tsx
  src/Components/Sign/SignRouterButton.tsx
  src/Components/Template Box/Box.tsx
  src/Components/Template Grid/Grid.tsx
  src/Components/Template Grid/Top.tsx
  src/Components/Template Modern/Modern.tsx
  src/Components/Template Standard/Standard.tsx
  src/app/(authlayout)/layout.tsx
  src/app/(nonAuthLayout)/signin/page.tsx
  src/app/(nonAuthLayout)/signupMethod/page.tsx
  src/app/page.tsx
Labels: 문서, 새로운 기능

#223 login Check 문제 및 skillTag input 검색기능 추가 및 중복 등록 불가 작성
  src/Components/Header.tsx
  src/Components/MyPage/Buttons.tsx
  src/Components/MyPage/Introduction.tsx
  src/Components/MyPage/Navigation.tsx
  src/Components/MyPage/PortfolioUrl.tsx
  src/Components/MyPage/Project.tsx
  src/Components/MyPage/UserInfo.tsx
  src/app/(authlayout)/layout.tsx
  src/app/(authlayout)/mypage/page.tsx
  src/app/community/layout.tsx
  src/app/create/layout.tsx
  src/app/page.tsx
  src/app/share/layout.tsx
  src/hooks/guest/useGuestButton.ts
  src/hooks/mypage/useInfo.ts
  src/hooks/mypage/useLoginCheck.ts
  src/hooks/mypage/usePortfolioQuery.ts
  src/util/toast.ts
  tailwind.config.ts
Labels: 버그, 문서, 새로운 기능

#229 Template
  src/Components/DetailPage/Portfolio_detail.tsx
  src/Components/Footer.tsx
  src/Components/MainPage/Bottom.tsx
  src/Components/MainPage/MiddleImage.tsx
  src/Components/MainPage/MiddleLeft.tsx
  src/Components/Template Box/Bottom.tsx
  src/Components/Template Box/Middle.tsx
  src/Components/Template Box/Top.tsx
  src/Components/Template Box/URL.tsx
  src/Components/Template Grid/Middle.tsx
  src/Components/Template Grid/Top.tsx
  src/Components/Template Grid/URL.tsx
  src/Components/Template Modern/Bottom.tsx
  src/Components/Template Modern/Middle.tsx
  src/Components/Template Modern/Top.tsx
  src/Components/Template Modern/URL.tsx
  src/Components/Template Standard/Middle.tsx
  src/Components/Template Standard/Top.tsx
  src/Components/Template Standard/URL.tsx
  src/Components/TimeLine/ProjectTimelineItem.tsx
  src/Components/TimeLine/UserProject.tsx
  src/Components/TimeLine/WorkExperience.tsx
  src/Components/TimeLine/WorkTimelineItem.tsx
Labels: 문서, 새로운 기능

#230 Feature/community
  src/Components/Community/Cards.tsx
  src/Components/Community/Carousel.tsx
  src/Components/Community/DeleteModal.tsx
  src/Components/Community/Dropdown.tsx
  src/Components/Community/Filter.tsx
  src/Components/Community/JobFilter.tsx
  src/Components/DetailPage/CommentInput.tsx
  src/Components/DetailPage/Comments.tsx
  src/Components/DetailPage/Modal.tsx
  src/Components/DetailPage/PortfolioDetail.tsx
  src/app/community/page.tsx
  src/hooks/community/useDelete.ts
  src/hooks/useSupabaseRange.ts
  src/store/detailStore.ts
  src/store/pageStore.ts
  src/store/portfolioInfoStore.ts
  src/types/PortfolioInfo.ts
  src/types/Supabase.ts
  src/util/supabase/community_filter_DB.ts
  src/util/supabase/detail_supabase_DB.ts
  tailwind.config.ts
Labels: 문서, 새로운 기능

#231 Feature/community
  src/Components/Community/Cards.tsx
  src/Components/Community/Carousel.tsx
  src/Components/Community/DeleteModal.tsx
  src/Components/DetailPage/CommentInput.tsx
  src/Components/DetailPage/Comments.tsx
  src/Components/DetailPage/Modal.tsx
  src/Components/DetailPage/PortfolioDetail.tsx
  tailwind.config.ts
Labels: 문서, 새로운 기능

#256 모달 바깥 쪽 클릭시 모달이 닫히는 기능 작성
  package.json
  src/Components/Header.tsx
  src/Components/MyPage/Buttons.tsx
  src/Components/MyPage/Preview.tsx
  src/Components/MyPage/TemplateSelect.tsx
  src/app/(nonAuthLayout)/layout.tsx
  src/app/confirmEmail/page.tsx
  src/hooks/mypage/useTemplateSelect.ts
  src/hooks/useMouseClickClose.ts
  src/middleware.ts
  yarn.lock
Labels: 문서, 새로운 기능

#261 로그인, 회원가입 반응형
  src/Components/Sign/SignPersonalInfoCheck.tsx
  src/Components/Sign/SignSelectSex.tsx
  src/app/(nonAuthLayout)/(findPassword)/findEmail/page.tsx
  src/app/(nonAuthLayout)/(findPassword)/passwordChange/page.tsx
  src/app/(nonAuthLayout)/confirmEmail/page.tsx
  src/app/(nonAuthLayout)/signin/page.tsx
  src/app/(nonAuthLayout)/signup/page.tsx
  src/app/(nonAuthLayout)/signupMethod/page.tsx
  src/app/(nonAuthLayout)/socialSetting/page.tsx
  src/app/(nonAuthLayout)/welcome/page.tsx
Labels: 문서, 새로운 기능

#262 포트폴리오 등록로직의 포트폴리오 반복 제거 및 textarea 개행 css 적용
  public/favicon.ico
  src/Components/Template Box/Bottom.tsx
  src/Components/Template Box/Middle.tsx
  src/Components/Template Grid/Middle.tsx
  src/Components/Template Modern/Bottom.tsx
  src/Components/Template Modern/Middle.tsx
  src/Components/Template Standard/Middle.tsx
  src/Components/TimeLine/ProjectTimelineItem.tsx
  src/Components/TimeLine/WorkExperience.tsx
  src/Components/TimeLine/WorkTimelineItem.tsx
  src/app/(authlayout)/layout.tsx
  src/hooks/mypage/useInfo.ts
  src/types/PortfolioInfo.ts
Labels: 문서

#266 Feature/community
  src/Components/Community/Cards.tsx
  src/Components/Community/Carousel.tsx
  src/Components/DetailPage/Modal.tsx
  src/Components/DetailPage/PortfolioDetail.tsx
  src/Components/Template Box/Bottom.tsx
  src/Components/Template Box/Box.tsx
  src/Components/Template Box/Top.tsx
  src/Components/Template Box/URL.tsx
  src/Components/Template Grid/Grid.tsx
  src/Components/Template Modern/Bottom.tsx
  src/Components/Template Modern/Middle.tsx
  src/Components/Template Modern/Modern.tsx
  src/Components/Template Modern/Top.tsx
  src/Components/Template Standard/Standard.tsx
  src/Components/Template Standard/URL.tsx
  src/Components/TimeLine/ProjectTimelineItem.tsx
Labels: 문서

#268 토스트 작성 및 커뮤니티 모달 확인
  src/Components/DetailPage/LikeShare.tsx
  src/Components/DetailPage/Modal.tsx
  src/Components/MyPage/Buttons.tsx
  src/hooks/mypage/useInfo.ts
  src/hooks/mypage/useLoginCheck.ts
  src/util/urlCopy.ts
  tailwind.config.ts
Labels: 문서

#271 자잘한 업데이트
  src/Components/DetailPage/Modal.tsx
  src/Components/Guest/Buttons.tsx
  src/Components/MyPage/Buttons.tsx
  src/Components/MyPage/Careers.tsx
  src/Components/MyPage/Introduction.tsx
  src/Components/MyPage/Preview.tsx
  src/Components/MyPage/TemplateSelect.tsx
  src/app/(nonAuthLayout)/guest/result/page.tsx
  src/hooks/mypage/useInfo.ts
  src/hooks/mypage/usePortfolioQuery.ts
  src/hooks/useUserCheck.ts
  src/types/PortfolioInfo.ts
  src/util/serverUserCheck.ts
  src/util/sign/socialLogin.ts
  src/util/toast.ts
Labels: 문서

#272 Sign 페이지 오류 수정 및 주석 삭제
  src/app/(nonAuthLayout)/(findPassword)/findEmail/page.tsx
  src/app/(nonAuthLayout)/(findPassword)/passwordChange/page.tsx
  src/app/(nonAuthLayout)/signin/page.tsx
  src/app/api/send/route.ts
  src/app/auth/confirm/route.ts
  src/app/confirmEmail/page.tsx
  src/app/socialSetting/page.tsx
  src/util/sign/signCheckUserPortfolio.ts
Labels: 버그

#273 헤더 반응형 수정, 자잘한 css 수정
  public/assets/image/menu.svg
  src/Components/Footer.tsx
  src/Components/Header.tsx
  src/Components/HeaderNonAuth.tsx
  src/Components/MainPage/Cover.tsx
  src/Components/MainPage/MiddleBottom.tsx
  src/Components/MainPage/Recommendation.tsx
  src/Components/Template Box/Middle.tsx
  src/app/page.tsx
Labels: 문서, 새로운 기능

#274 반응형 수정 및 create, share 링크 템플릿 추가
  src/Components/MyPage/Buttons.tsx
  src/Components/MyPage/Careers.tsx
  src/Components/MyPage/Navigation.tsx
  src/Components/MyPage/Preview.tsx
  src/Components/MyPage/UserInfo.tsx
  src/app/create/[id]/page.tsx
  src/app/layout.tsx
  src/app/share/[id]/page.tsx
  src/hooks/mypage/usePortfolioQuery.ts
Labels: 문서

#281 Template 상세페이지 클래스 수정, 로그인 컴포넌트 위치 수정
  src/Components/DetailPage/PortfolioDetail.tsx
  src/Components/Guest/Buttons.tsx
  src/Components/MyPage/Buttons.tsx
  src/Components/MyPage/Preview.tsx
  src/Components/Sign/SignInputItem.tsx
  src/Components/Sign/SignInputNonStar.tsx
  src/Components/Sign/SignSelectSex.tsx
  src/Components/Template/Box/Bottom.tsx
  src/Components/Template/Box/Box.tsx
  src/Components/Template/Box/Middle.tsx
  src/Components/Template/Box/Top.tsx
  src/Components/Template/Box/URL.tsx
  src/Components/Template/Grid/Bottom.tsx
  src/Components/Template/Grid/Grid.tsx
  src/Components/Template/Grid/Middle.tsx
  src/Components/Template/Grid/TimeLine/ProjectTimelineItem.tsx
  src/Components/Template/Grid/TimeLine/UserProject.tsx
  src/Components/Template/Grid/TimeLine/WorkExperience.tsx
  src/Components/Template/Grid/TimeLine/WorkTimelineItem.tsx
  src/Components/Template/Grid/Top.tsx
  src/Components/Template/Grid/URL.tsx
  src/Components/Template/Modern/Bottom.tsx
  src/Components/Template/Modern/Middle.tsx
  src/Components/Template/Modern/Modern.tsx
  src/Components/Template/Modern/Top.tsx
  src/Components/Template/Modern/URL.tsx
  src/Components/Template/Standard/Middle.tsx
  src/Components/Template/Standard/Standard.tsx
  src/Components/Template/Standard/Top.tsx
  src/Components/Template/Standard/URL.tsx
  src/app/(nonAuthLayout)/(findPassword)/passwordChange/page.tsx
  src/app/(nonAuthLayout)/guest/result/page.tsx
  src/app/create/[id]/page.tsx
  src/app/share/[id]/page.tsx
  src/app/socialSetting/page.tsx
Labels: 문서, 새로운 기능

#284 Template
  src/Components/Template/Box/Top.tsx
  src/Components/Template/Modern/Top.tsx
  src/Components/Template/TimeLine/ProjectTimelineItem.tsx
  src/Components/Template/TimeLine/UserProject.tsx
  src/Components/Template/TimeLine/WorkExperience.tsx
  src/Components/Template/TimeLine/WorkTimelineItem.tsx
  src/app/(nonAuthLayout)/signup/page.tsx
Labels: 문서, 새로운 기능
